#!/bin/bash

function fibRec {
		param=$1
		nb=1
		if [[ $param = "0" || $param < "0" ]]
		then
			echo "you dont use this as parametr"
			echo "write a parametr;Example: 3"
			read param
			fibRec $param
		else
			let "ut=$param+0" 2>/dev/null
			if [[ $ut = "0" ]]
			then
				echo "you dont use this parametr"
				echo "write a parametr;Example: 3"
				read param
				fibRec $param
			else	
				if [[ $param = 1 || $param = 2 ]]
				then	echo "1"
				else
					if [[ $param -lt "25" ]]; then 2>/dev/null
						let "x=$param-2"
						let "y=$param-1"
						echo $[ $(fibRec $x) + $(fibRec $y) ]
					else
						echo "you dont use this parametr"
						echo "write a parametr;Example: 3"
						read param
						fibRec $param
					fi
				fi
			fi
		fi
}

fibRec $1
