#!/bin/bash 

source simple.lib

function main
{
	if (( $# == 1 ))
		then if (( $1 > 0 ))
			then echo "simple $1: $(simple $1)"
			return 0
		fi
	fi
	echo "Вводимое число должно быть больше нуля!"
	return 1
}

main $1

